### ISSUE TITLE
Remove bok-choy usage

### ISSUE THREAD

**Issue by salman2013** [openedx-unsupported/edx-analytics-dashboard#1509]
This repo's acceptance tests still use the bok-choy framework, which https://github.com/openedx/public-engineering/issues/13. The bok-choy repository is no longer being maintained, and it will soon be archived.

Once the bok-choy repo is archived, the acceptance tests should continue working, as we will not be removing the package's releases from PyPI. For long-term maintainability of this repo, though, the tests should eventually be upgraded to a non-bok-choy testing framework or removed.

**Comment by feanil** [comment]
This was fixed via https://github.com/openedx/edx-analytics-dashboard/pull/1527
