### ISSUE TITLE
How to make dashboard work with edx-platform?

### ISSUE THREAD

**Issue by flmeng1978** [openedx-unsupported/edx-analytics-dashboard#215]
Hi, clintonb. I'm fl_meng in IRC. Yesterday I ask you a question. You give me a pdf  which named "Open edX Analytics" and I read it. Now, I'm confused how to assemble these module correctly?

**Comment by clintonb** [comment]
@flmeng1978 we will be releasing documentation in the next 1-2 months.

**Comment by hardikchauhan-** [comment]
@flmeng1978

can you please give me pdf file for Open edX Analytics.
