### ISSUE TITLE
make develop have some issue

### ISSUE THREAD

**Issue by jsgang** [openedx-unsupported/edx-analytics-dashboard#229]
pip install -q -r requirements/base.txt --exists-action w
  Could not find a tag or branch 'ece149d706aaf812afd6b39872cf01fd294b2038', assuming commit.
 Could not find a tag or branch '0d7847f9dfa2281640527b4dc51f5854f950f9b7', assuming commit.
  Could not find a tag or branch 'd45d0bd8d64c69531be69178b9505b5d38806ce0', assuming commit.
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_dmt/bpython/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-HSfsVv-record/install-record.txt --single-version-externally-managed --compile failed 
Who can help me? Thanks

**Comment by clintonb** [comment]
When did you last pull from master? There was an issue with the django-announcements requirement that was fixed last week. Try pulling from master and reinstalling the requirements.

**Comment by jsgang** [comment]
I'm install at last week. I will try again,thanks!

**Comment by clintonb** [comment]
@jsgang I assume this issue has been resolved. If not, please comment to reopen.

**Comment by clintonb** [comment]
@jsgang The error log you posted doesn't provide much detail. However, before we continue trying to debug the dashboard installation, do you actually have the API and data pipeline setup? The dashboard is unusable without it.

**Comment by jsgang** [comment]
I use the last commit,I have some issue
npm install
./node_modules/.bin/bower install
bower extra-resolution Unnecessary resolution: cldrjs#0.3.10
pip install -q -r requirements/base.txt --exists-action w
Could not find a tag or branch '0d7847f9dfa2281640527b4dc51f5854f950f9b7', assuming commit.
Could not find a tag or branch 'd45d0bd8d64c69531be69178b9505b5d38806ce0', assuming commit.
Command /usr/bin/python -c "import setuptools, tokenize; file='/edx/app/analytics-dashboard/src/i18n-tools/setup.py'; exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" develop --no-deps failed with error code 1 in /edx/app/analytics-dashboard/src/i18n-tools
Storing debug log for failure in /home/dmt/.pip/pip.log
make: **\* [requirements] Error 1
