### ISSUE TITLE
assuming commit

### ISSUE THREAD

**Issue by jsgang** [openedx-unsupported/edx-analytics-dashboard#238]
I use the last commit,I have some issue
npm install
./node_modules/.bin/bower install
bower extra-resolution      Unnecessary resolution: cldrjs#0.3.10
pip install -q -r requirements/base.txt --exists-action w
  Could not find a tag or branch '0d7847f9dfa2281640527b4dc51f5854f950f9b7', assuming commit.
  Could not find a tag or branch 'd45d0bd8d64c69531be69178b9505b5d38806ce0', assuming commit.
Command /usr/bin/python -c "import setuptools, tokenize; **file**='/edx/app/analytics-dashboard/src/i18n-tools/setup.py'; exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" develop --no-deps failed with error code 1 in /edx/app/analytics-dashboard/src/i18n-tools
Storing debug log for failure in /home/dmt/.pip/pip.log
make: **\* [requirements] Error 1

**Comment by clintonb** [comment]
This is related to #229. Please leave your comments there.
