### ISSUE TITLE
Problem of OperationalError at /test/auto_auth/

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-dashboard#266]
Can anyone one help me to slove the problem ? Thank you very much !!
![screenshot from 2015-02-27 03 44 17](https://cloud.githubusercontent.com/assets/9279378/6400477/121a4bc8-be34-11e4-9851-d0674dd9c062.png)

**Comment by clintonb** [comment]
@jeremy55662004 Check your database settings. The user you are using does not have write access to the database you are using.

**Comment by jeremy55662004** [comment]
Thank you Clintons !!  :+1:   But i have another problem i post on next issue.
