### ISSUE TITLE
Problem of how to login to insights

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-dashboard#268]
When i visit http://localhost:9000/test/auto_auth/ to create and login as a new user and i got the picture below:
![2015-02-27 9 36 31](https://cloud.githubusercontent.com/assets/9279378/6413485/e9732afe-beca-11e4-9348-0e68e74180b9.png)

but when i log out 
![2015-02-27 9 37 11](https://cloud.githubusercontent.com/assets/9279378/6413501/118c57b8-becb-11e4-8279-ff31087c3657.png)

then clicked the log in i got the page not find error
![2015-02-27 9 37 28](https://cloud.githubusercontent.com/assets/9279378/6413520/3fb96338-becb-11e4-845e-fea84bff9032.png)

My question is how to create a new user then log in to the insights ? 
I think the problem is probably about the oauth2.

Thank you for helping me !!

**Comment by clintonb** [comment]
@jeremy55662004 Before we get too deep into figuring Insights auth, do you actually have data for your API? If not, setting up Insights is a pretty moot point. It absolutely will not work without the data API.

**Comment by jeremy55662004** [comment]
Actually i haven't set my edX-pipeline yet because i always stuck in setting configuration on my cluster on Amazon and just little difficult to set up .So you mean that i should set up my pipeline first then i will get the data for API right ? Thank you for helping me to figure out this. :D

**Comment by clintonb** [comment]
The pipeline is essential. You should work on setting it up before anything else.
