### ISSUE TITLE
CommandError ! Can anyone help me Thanks !

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-dashboard#308]
When i was installing edx-analytics-dashboard on how to install and run the analytics backend locally there was an error below when i had a command (make validate) : 
![default](https://cloud.githubusercontent.com/assets/9279378/7666228/2c6a3286-fc0f-11e4-8413-0be972c2993c.png)

I have no idea how to fix it ! If someone can give me a tip and i will be grateful.

Thanks !!

**Comment by dsjen** [comment]
Hi, I believe that the assets haven't been created yet.  Would you try running `make static` and then try again?

**Comment by jeremy55662004** [comment]
Hi, Dennis
Thank you for answering me ! But when i tried  running  make static i got another error :
![screenshot from 2015-05-20 17 33 40](https://cloud.githubusercontent.com/assets/9279378/7722858/856d061a-ff16-11e4-9ee2-341a3090331c.png)

where can i set COMPRESS_ENABLED ? and there was an error after i typed make validate.
![screenshot from 2015-05-20 17 38 39](https://cloud.githubusercontent.com/assets/9279378/7722924/168c54a2-ff17-11e4-807d-1e95ee6f271a.png)

Thanks !!

**Comment by dsjen** [comment]
Hi Jeremy, you should be able to run the compress step with `python manage.py compress --force`.  Can you give that a try?  It came take a few minutes to run.  I actually think you may have been able to compress with the `make validate` step though, as early on the compression step takes place, followed by the python tests.  They seem to have passed and the error that you're seeing in in a javascript test that is oddly failing.  Did you modify any of the javascript files?

Regardless, if it's only the test that's failing, you should be able to run Insights assuming you have the API and data ready to go.
- Dennis

**Comment by jeremy55662004** [comment]
Thank you for all your assistance Dennis !
i modified the Makefile to add (python manage.py compress --force) to the Makefile
![screenshot from 2015-05-21 17 45 13](https://cloud.githubusercontent.com/assets/9279378/7745941/67965fb2-ffe1-11e4-8965-7d65777410a2.png)

then after i ran (make static) it was succeful.
![screenshot from 2015-05-21 17 38 11](https://cloud.githubusercontent.com/assets/9279378/7746049/188d7864-ffe2-11e4-94fc-ced3abae17e8.png)

but after the (make validate) command there was a same error !
![screenshot from 2015-05-21 17 57 47](https://cloud.githubusercontent.com/assets/9279378/7746200/1af8657c-ffe3-11e4-9042-3fc459d6e583.png)

I didn't modify any of the javascript files and i only modified the Makefile to add the (python manage.py compress --force) command.I think that it's only the test that's failing. So do you mean that i still can run my insights normally ?

Thanks !!
by jeremy

**Comment by dsjen** [comment]
Hi Jeremy,

You should be able to run Insights normally, even though this test is failing, assuming you have the API and the data all set up.

Would you let me know your time zone please?  I suspect there might be a conversion issue causing the javascript test to fail.

Thanks,
Dennis

**Comment by jeremy55662004** [comment]
Hi Dennis,

Sure ! I'm from Taiwan and my time zone is  UTC/GMT +8 hours. 
Thank you so much Dennis !

by Jeremy

**Comment by dsjen** [comment]
https://github.com/edx/edx-analytics-dashboard/pull/313 address the failing javascript test due to timezone.

**Comment by jeremy55662004** [comment]
Hi Dennis,
Thank you and edX team for helping me! Maybe i will try again later ! :+1: 

Thanks
by Jeremy
