### ISSUE TITLE
I got error 

### ISSUE THREAD

**Issue by bluerespect** [openedx-unsupported/edx-analytics-dashboard#318]
I installed 
edx/edx-analytics-data-api
edx/edx-analytics-pipeline
edx/edx-analytics-data-api-client
edx/edx-analytics-dashboard widthout error

refer to Running the analytics backend locally 
(https://github.com/edx/edx-analytics-pipeline/wiki/Running-the-analytics-backend-locally)

but I can't login after "./manage.py runserver 0.0.0.0:9000" 
![image](https://cloud.githubusercontent.com/assets/5857588/7975769/e9aaec4a-0aac-11e5-87d7-f1a6757879c1.png)

I set Oauth2 and /edx-analytics-dashboard/analytics_dashboard/settings/local.py

![image](https://cloud.githubusercontent.com/assets/5857588/7975746/a557bc8a-0aac-11e5-829f-10c0252627f1.png)

![image](https://cloud.githubusercontent.com/assets/5857588/7975754/bd8423ca-0aac-11e5-8179-0db43c0fa603.png)

![image](https://cloud.githubusercontent.com/assets/5857588/7975763/d68fccf2-0aac-11e5-93b6-701797d848b6.png)

What Is the problem??

**Comment by dsjen** [comment]
Hi, I'm sorry to hear about the problems in setting up Insights.  What is the error screen that you're seeing when the login fails?  Is Insights redirecting to the LMS login page successfully?

Thanks,
Dennis

**Comment by sssso** [comment]
I want to sso system 
So, I want to use insights without login after cms or lms login
