### ISSUE TITLE
I want to be analytics-dashboard to work without logging in

### ISSUE THREAD

**Issue by bluerespect** [openedx-unsupported/edx-analytics-dashboard#324]
I want to be analytical to work without logging in
(I've installed the analysis tools and edx to one server, https://github.com/edx/edx-analytics-pipeline/wiki/Running-the-analytics-backend-locally)

I refer https://github.com/edx/edx-analytics-pipeline/wiki/Configuring-Insights-for-Open-ID-Connect-SSO-with-LMS

after setting, I see
![image](https://cloud.githubusercontent.com/assets/5857588/8324493/16570802-1a8c-11e5-846b-99c6faa186e7.png)

Did I do something wrong?

**Comment by dsjen** [comment]
Hi, it looks like your LMS seems to be not loading properly.  What is the error that you're getting?  Are you getting redirected to this page after trying to log into Insights?  Are you able to login, and if so, where are you redirected to another page?

Thanks,
Dennis
