### ISSUE TITLE
ImportError: No module named __pkginfo__ 

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-dashboard#328]
Hi, 
I got some errors when i reinstalled my edx analytics dashboard. I typed the command make validate and there is an error below : 

![2015-07-01 2 26 15](https://cloud.githubusercontent.com/assets/9279378/8438484/a94d6db6-1f98-11e5-99f9-0bc5c111a639.png)

I have no idea how to fix it ! If someone can give me a tip and i will be grateful.

Thanks!!

by jeremy

**Comment by dsjen** [comment]
Hi Jeremy, I haven't seen this error before.  Do you know what version of pylint you're using (e.g. pip freeze | grep pylint)?  I'm on pylint==1.4.1.
- Dennis

**Comment by jeremy55662004** [comment]
Hi Dennis, yes!  i'm also on pylint==1.4.1.

![2015-07-01 3 21 12](https://cloud.githubusercontent.com/assets/9279378/8449536/d59786b0-2004-11e5-95d4-b5a759396288.png)

I think the bug maybe has no influence for me because i also has the user interface of my analytics dashboard.

Thanks  Dennis !!

**Comment by dsjen** [comment]
Hi Jeremy, 

You're absolutely right in that you can run the dashboard without resolving this issue.  The linter having failed shouldn't affect your ability to use the dashboard.  It looks like you ran the pipe freeze command from the devstack.

Running it from the "edx-analytics-dashboard" environment will return the pylint version that the dashboard is using.

Thanks,
Dennis

**Comment by jeremy55662004** [comment]
Hi Dennis,

I'm running it form the "edx-analytics-dashboard" environment also return the version of pylint is 1.4.1.
![2015-07-01 10 46 42](https://cloud.githubusercontent.com/assets/9279378/8457331/595ee360-2043-11e5-964d-99dc100b3135.png)

You're right ! I believe that the linter having failed shouldn't affect my ability to use the dashboard and i think that we can close this issue.

Thank you for helping me !!
Jeremy

**Comment by dsjen** [comment]
Hi Jeremy, thanks for checking that.  I'm confused about what might be wrong.  Have you run "make develop" yet?  It almost seems like a pylint dependency is missing.

**Comment by jeremy55662004** [comment]
Hi Dennis,

Yes, first i have run "make develop" then i ran the command "make validate". I agree that it seems like pylint dependency is missing but i keep trying to find what dependency missing will cause the error and i still have no idea.

Thanks

**Comment by dsjen** [comment]
Hi Jeremy,

Here's the output of pip freeze for me:

```
Django==1.7.4
Jinja2==2.7.3
MarkupSafe==0.23
PyJWT==1.1.0
PyYAML==3.11
Pygments==1.6
South==1.0
Sphinx==1.1.3
Unidecode==0.04.16
argparse==1.2.1
astroid==1.3.4
awesome-slugify==1.6.2
backports.ssl-match-hostname==3.4.0.2
bok-choy==0.3.1
bpython==0.12
browsermob-proxy==0.6.0
certifi==14.05.14
coverage==3.7.1
cssselect==0.9.1
ddt==1.0.0
-e git+https://github.com/RahimovIR/django-announcements.git@54657f27c043362be2f21a9c34a1e96409f0c9c9#egg=django_announcements-master
django-appconf==0.6
django-braces==1.2.2
django-compressor==1.4
django-countries==3.1.1
django-debug-toolbar==1.2.2
django-devserver==0.8.0
django-discover-runner==0.4
django-dynamic-fixture==1.8.1
-e git+https://github.com/edx/django-lang-pref-middleware.git@6f873db33ca32f924dc7004a58bf3845f4f55605#egg=django_lang_pref_middleware-0.1.0
django-libsass==0.2
django-model-utils==1.5.0
django-nose==1.3
django-soapbox==1.1
django-waffle==0.10
docutils==0.11
edx-analytics-data-api-client==0.6.1
edx-auth-backends==0.1.2
edx-server-api-client==0.1.0
elasticsearch==1.4.0
git-review==1.23
httplib2==0.9
httpretty==0.8.4
-e git+https://github.com/edx/i18n-tools.git@0d7847f9dfa2281640527b4dc51f5854f950f9b7#egg=i18n_tools-dev
js-test-tool==0.1.5
libsass==0.5.1
logilab-astng==0.24.3
logilab-common==0.61.0
logutils==0.3.3
lxml==3.3.5
mock==1.0.1
nose==1.3.4
nose-exclude==0.2.0
nose-ignore-docstring==0.2
oauthlib==0.6.3
-e git+https://github.com/edx/opaque-keys.git@d45d0bd8d64c69531be69178b9505b5d38806ce0#egg=opaque_keys-dev
path.py==5.2
pep257==0.4.1
pep8==1.6.0
polib==1.0.5
pyinstrument==0.13.1
pylint==1.4.1
pymongo==2.7.2
pyquery==1.2.9
python-openid==2.2.5
python-social-auth==0.2.3
pytz==2014.4
regex==2014.12.24
requests==2.2.0
requests-oauthlib==0.4.1
restnavigator==0.2.0
selenium==2.44.0
simplejson==3.5.3
six==1.7.2
slumber==0.6.2
sphinxcontrib-napoleon==0.2.4
splinter==0.6.0
sqlparse==0.1.11
stevedore==1.0.0
sure==1.2.7
testfixtures==4.1.2
tornado==4.1
transifex-client==0.10
unittest2==0.8.0
uritemplate==0.6
urllib3==1.10.2
wsgiref==0.1.2
```

I'm not sure if it's helpful.  Perhaps we could compare to see if anything seems off between environments.

Thanks,
Dennis

**Comment by jeremy55662004** [comment]
HI, Dennis

Here is my output for pip freeze under my edx-analytics-dashboard environment. I find that my logilab-common==1.0.0 isn't same as yours (logilab-common==0.61.0). Can i use the latest one ?  or i can use "pip uninstall logilab-common" then "pip install logilab-common==0.61.0" .

Django==1.7.4
Pillow==2.8.2
PyJWT==1.3.0
PyYAML==3.11
Pygments==2.0.2
Unidecode==0.04.18
argparse==1.2.1
astroid==1.3.6
awesome-slugify==1.6.2
backports.ssl-match-hostname==3.4.0.2
bok-choy==0.4.2
bpython==0.12
browsermob-proxy==0.6.0
certifi==2015.04.28
coverage==3.7.1
ddt==1.0.0
django-announcements==1.2.0
django-appconf==0.6
django-braces==1.2.2
django-compressor==1.4
django-countries==3.1.1
django-debug-toolbar==1.2.2
django-dynamic-fixture==1.8.1
django-lang-pref-middleware==0.1.0
django-libsass==0.2
django-model-utils==1.5.0
django-nose==1.3
django-soapbox==1.1
django-waffle==0.10
edx-analytics-data-api-client==0.6.1
edx-auth-backends==0.1.2
elasticsearch==1.4.0
httplib2==0.9.1
httpretty==0.8.4
i18n-tools==0.1
libsass==0.5.1
logilab-common==1.0.0
logutils==0.3.3
mock==1.0.1
needle==0.3
nose==1.3.4
nose-exclude==0.2.0
nose-ignore-docstring==0.2
oauthlib==0.7.2
opaque-keys==0.1.1
path.py==7.3
pbr==1.2.0
pep257==0.4.1
pep8==1.6.0
polib==1.0.6
psutil==2.2.1
pylint==1.4.1
pymongo==3.0.2
python-openid==2.2.5
python-social-auth==0.2.3
pytz==2015.4
regex==2015.06.24
requests==2.7.0
requests-oauthlib==0.5.0
selenium==2.46.0
six==1.9.0
slumber==0.6.2
sqlparse==0.1.15
stevedore==1.5.0
sure==1.2.7
testfixtures==4.1.2
tornado==4.2
transifex-client==0.10
unittest2==0.8.0
urllib3==1.10.4
wsgiref==0.1.2

Thanks !
Jeremy

**Comment by jeremy55662004** [comment]
Thanks Dennis !! We fix the error ! I should install logilab-common==0.61.0.
![2015-07-02 12 30 59](https://cloud.githubusercontent.com/assets/9279378/8459738/d8635c0a-2051-11e5-9b22-b7144112f841.png)

Thank you for helping me !
Jeremy

**Comment by dsjen** [comment]
I'm so glad that solved the problem!  I'm going to submit a pull request to set the version of logilab-common so others don't run into the same problem.
