### ISSUE TITLE
error in installing edx-analytics

### ISSUE THREAD

**Issue by isural** [openedx-unsupported/edx-analytics-dashboard#354]
Hi,I got the following error while executing make develop command. I have edx installed and running on system. what am I missing to do?  I tried in -d (debug mode) but no further information i can get.

edxapp@moocs:~/edx-analytics$ make develop
npm install
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
./node_modules/.bin/bower install
bower cldrjs          extra-resolution Unnecessary resolution: cldrjs#0.4.0
pip install -q -r requirements/base.txt --exists-action w
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
    Command "/edx/app/edxapp/venvs/edxapp/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-u_m0V1/libsass/setup.py';exec(compile(getattr(tokenize, 'ope
n', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-kARC69-record/install-record.txt --single-version-externally-managed --com
pile --install-headers /edx/app/edxapp/venvs/edxapp/include/site/python2.7" failed with error code 1 in /tmp/pip-build-u_m0V1/libsass
make: **\* [requirements] Error 1

Thnak you very much for your help.
Irfan

**Comment by dsjen** [comment]
Hi Irfan,

Are you installing Insights in the edx devstack?  I'm not sure why you're getting this exact error, but I'd try doing this outside of the edx devstack in a separate virtual environment.

Do you have the analytics pipeline up and running?  Installing Insights won't be particularly satisfying without any data, and you'll need to install the pipeline first.

We just released an analytics devstack, http://edx-installing-configuring-and-running.readthedocs.org/en/latest/devstack/analytics_devstack.html, which has all the components to get a system set up if you'd like to give it a try.  It's newly release and feedback would be very welcome.

Thanks,
Dennis

**Comment by isural** [comment]
Hi Dennis,

Thank you for your reply. No I am not using edx devstack. I just follow the guide here https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation 

After that I tried to download analytics source and execute the command as given in github (make develop)

is this means in order to run edx-analytics I need to install on devstack? I really confused about vagrant and virtualbox stuff that's why I prefer to install directly on machine not virtualbox.

Thanks for your help

Irfan

**Comment by dsjen** [comment]
Hi Ifran,

Sorry for the confusion.  You can certainly install Insights and the analytics pipeline outside of devstack.  I just thought it would be easier to get your system up and running by using the analytics devstack (different through the standard edX devstack), http://edx-installing-configuring-and-running.readthedocs.org/en/latest/devstack/analytics_devstack.html.

If you'd rather not use a virtual machine, then you'll need to have the pipeline installed, the data api, and Insights.  If you didn't install the pipeline, you'd not have any data to provide to Insights.

I hope that's helpful.  Please let me know if you have any questions.

Thanks,
Dennis

**Comment by isural** [comment]
Hi Dennis,

Thank you for your reply. It is all clear now. Is there any documentation about how to install pipeline, data api and insights? I just don't want to find the way by experiential , each time my edx goes down and  it takes too much time to get it up and running.  

Your help is appreciated 
Thanks
Irfan

**Comment by mulby** [comment]
Hi Ifran, we don't currently have very clear instructions for installing these components. The best we have is this wiki page:

https://openedx.atlassian.net/wiki/display/OpenOPS/edX+Analytics+Installation

These instructions are for a very basic (small scale) installation and are not very well supported, unfortunately it's all we have at the moment.

Thanks,
-Gabe
