### ISSUE TITLE
Can't Login Insight Analystic Page

### ISSUE THREAD

**Issue by nda888** [openedx-unsupported/edx-analytics-dashboard#410]
Hi everyone,

Im using bitnami openedx to deploy course online

I install insight analystic tool follow the guide:
https://wiki.bitnami.com/Applications/Bitnami_Open_edX#How_to_install_edX_Analytics_Dashboard.3f
https://github.com/edx/edx-analytics-dashboard
https://openedx.atlassian.net/wiki/pages/viewpage.action?spaceKey=AN&title=Configuring+Insights+for+Open+ID+Connect+SSO+with+LMS

I set OAUTH_ENFORCE_SECURE = false in lms.env.json to use http

But unfortunately when i login
 -edx.abc.com:9000
 -Click login button
The issue alert "**invalid_request The requested redirect didn't match the client settings**"

The LMS setting
url: http://edx.abc.com/
redirect: http://edx.abc.com/complete/edx-oidc

Please help me
Thanks so much

An,

**Comment by dsjen** [comment]
Hi An,

Sorry for the delay in responding.  We don't typically monitor this "issues" section and encourage questions to be sent to the [google group](https://groups.google.com/forum/#!forum/openedx-analytics) instead.

If you haven't solved this yet, one quick adjustment is that the redirect probably needs a "/" at the end (e.g. http://edx.abc.com/complete/edx-oidc/).
- Dennis

**Comment by nda888** [comment]
Hi Dennis

Im using bitnami Openedx cypress version to deploy

Following the guide bellow

https://wiki.bitnami.com/Applications/Bitnami_Open_edX#How_to_install_edX_Analytics_Dashboard.3f

I tried your solution but no work

An,

**Comment by dsjen** [comment]
Sorry, that didn't work!  Please follow up on the [google group](https://groups.google.com/forum/#!forum/openedx-analytics) for the analytics team.  Someone from the list might be able to help you, as someone from the team will be dedicating time to investigating issues like this each week.
