### ISSUE TITLE
Removing private name out of the transcript

### ISSUE THREAD

**Issue by htdinh** [openedx-unsupported/edx-analytics-dashboard#457]
I am the Hung Tu the translator listed first in the following code. I want to remove my name from that publicly available code. Can someone help me do so? Thank you. 
edx-analytics-dashboard/analytics_dashboard/conf/locale/vi/LC_MESSAGES/djangojs.po

**Comment by dsjen** [comment]
Hi Hung Tu,

Your name could be removed from the .po file, similar to what's done in https://github.com/edx/edx-analytics-dashboard/pull/431.  The only issue is that when we pull translations from transifex, the translator name will reappear.
- Dennis
