### ISSUE TITLE
'make develop' error

### ISSUE THREAD

**Issue by thatguynishant** [openedx-unsupported/edx-analytics-dashboard#516]
I used the bitnami image to run on a VPS and after cloning the git repository i am getting error while executing make develop.
`lunr.js#0.7.1 analytics_dashboard/static/bower_components/lunr.js

pip install -q -r requirements/base.txt --exists-action w

Command "/opt/edx-20160414-2/python/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-V6VIP3/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-yJZgpt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-V6VIP3/regex/

make: **\* [requirements] Error 1
`
please give me some help

**Comment by dsjen** [comment]
Hi @ndixit01,

I'm not familiar with the bitnami image, but I would suggest using the [analytics devstack](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/install_analytics.html) instead.  I'm not sure what these errors means unfortunately.
- Dennis
